# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  access_denied_listener:
    json: true
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    messages:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    exception_controller: 'fos_rest.exception.controller:showAction'
  view:
    view_response_listener: 'force'
    formats:
      json: true
      xml: true
